name: NationTech
version: 0.0.1
main: com.nationtech.NationTech
api-version: "1.20"
authors: [Poelsk, Santiago22022]
description: Un sistema de tecnología para naciones de Towny.
softdepend:
  - Towny
load: POSTWORLD